#####################################
# Nextflow CI Test for NML Pipeline #
#####################################
name: monkeypox-nf NML CI

on:
  pull_request: # Run on all pull requests
  push:
    branches: master
  schedule: # Run master monthly at 6am on the 15th
    - cron: 0 6 15 * *
      branches: master

jobs:
  pipeline-test:
    name: monkeypox-nf workflow test
    runs-on: ubuntu-latest

    # For conda
    defaults:
      run:
        shell: bash -el {0}

    steps:
    # Setup repo
    - uses: actions/checkout@v3
    - name: Create artifacts dir
      run: mkdir -p artifacts
    
    # Add conda, mamba, and nextflow
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        miniconda-version: "latest"
        activate-environment: nextflow
        python-version: 3.9
        mamba-version: "*"
        use-mamba: true
        channels: conda-forge,bioconda,defaults
    - name: Install Nextflow
      run: |
        mamba install nextflow
    - name: Nextflow Version
      run: | 
        nextflow -v
        conda --version
    # Check how repo looks incase there is an issue
    - name: List Files
      run: |
        ls -al ${{ github.workspace }}
    # Run Help Command
    - name: Pipeline Help CMD
      run: |
        nextflow run ./main.nf --help
    
    # Run Pipelines
    - name: Run Metagenomic Illumina Pipeline
      run: bash .github/scripts/run_mpx_pipeline.sh

    - name: Run Metagenomic Illumina Pipeline with Metadata
      run: bash .github/scripts/run_mpx_pipeline_metadata.sh

    - name: Done Pipelines
      run: echo "Done running pipelines"
